---
services:
  fakecd:
    image: registry.cn-chengdu.aliyuncs.com/jdsgame/fakecd
    container_name: fakecd
    restart: unless-stopped
    ports:
      - 5000:5000
    environment:
      - AUTH_TOKEN=THETOKEN # tr -dc 'A-Za-z0-9' </dev/urandom | head -c 32
    volumes:
      - /root/.docker/config.json:/root/.docker/config.json
      - /var/run/docker.sock:/var/run/docker.sock
      - /data/nginx:/app/nginx # example
      - /data/redis:/app/redis # example
    network_mode: bridge
